export const SHAREDO_EVENTS = [
  "sharedo.core.case.phase-changed",
  "sharedo.core.case.components.related-documents.data-changed",
  "sharedo.core.case.document-delivery-task-created",
  "sharedo.core.case.keyfacts.updated",
  "Sharedo.Core.Case.Participants.Updated",
  "sharedo.core.case.components.taskList.data-changed",
  "sharedo.core.case.sharedo-updated",
  "sharedo.core.case.forms.phase.phase-changed",
  "Sharedo.Core.Legal.Proceedings.Updated",
  "sharedo.legal.updated",
  "Sharedo.Core.Legal.Finance.Refresh",
  "Sharedo.Core.Case.Fees.Version.Updated",
  "sharedo.core.case.components.comments.content-updating",
  "sharedo.core.case.components.comments.content-update-complete",
  "Sharedo.Core.Legal.Participants.Updated",
  "sharedo.core.case.participants-reordered",
  "Sharedo.Core.Legal.Widgets.TaskList.data-changed",
  "Sharedo.Core.Legal.Incidents.Updated",
  "Sharedo.Core.Case.Widgets.Scorecards.Updated",
  "dynamic-radar-opening",
  "sharedo.updated",
  "sharedo.core.case.components.comments.comments-changed",
  "sharedo.core.case.components.portfolioList.data-changed",
  "core.case.plan-view.undo",
  "Sharedo.Core.Case.DataQuality.CallToActionDone",
  "sharedo.core.case.action-plan.changed",
  "Sharedo.Core.Case.ActionPlanActions.TaskCreatedFromCallToAction",
  "user-profile-check-external-accounts",
  "sharedo.core.case.components.user-availability-changed",
  "oauth-link-complete",
  "sharedo.shownotifications",
  "sharedo.bookmarks.updated",
  "time-recording.active-stopwatch.data-changed",
  "sharedo.core.case.components.comments.data-changed",
  "sharedo.core.case.components.comments.config-changed",
  "sharedo.core.case.components.comments.filter-changed",
  "sharedo.ui.framework.lync.statusChanged",
  "sharedo.core.case.components.user-profile-image-changed",
  "core.sharedo.affected",
  "sharedo.core.case.sharedo-created",
  "sharedo.core.case.refresh-ribbon",
  "sharedo.core.case.sharedo-toolbar-action-completed",
  "sharedo.core.case.action-plan.updated",
  "sharedo.core.case.action-plan.changing",
  "ko.bindingHandlers.groupPanelBehaviour.start",
  "ko.bindingHandlers.groupPanelBehaviour.complete",
  "Sharedo.Core.Case.Components.PortfolioBreakdownByTypeChart.chartBreakdownByPhase.select",
  "admin-list-views-updated",
  "sharedo.core.case.reassigned",
  "custom.sharedo.event.sync.formbuilder.updated"
].sort();

export const DefaultEvents = [
  {
    eventName: "Sharedo.Core.Case.DataQuality.CallToActionDone",
  },
  {
    eventName: "Sharedo.Core.Case.Participants.Updated",
  },
  {
    eventName: "sharedo.core.case.sharedo-updated",
  },
  {
    eventName: "sharedo.updated",
  },
  {
    eventName: "sharedo.core.case.phase-changed",
  },
  {
    eventName: "sharedo.core.case.components.taskList.data-changed",
  },
  {
    eventName: "sharedo.core.case.action-plan.updated",
  },
  {
    eventName: "sharedo.core.case.action-plan.changed",
  },
    {
    eventName: "sharedo.core.case.reassigned",
  },
  {
    eventName:"custom.sharedo.event.sync.formbuilder.updated"
  }
];

export const DefaultWidgets = [
    {
        "typeName": "Sharedo.Core.Case.Menus.Widgets.WorkItemRibbon",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.DataQuality.CaseWidget",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.FormBuilder.Widgets.Standard",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Visualisation.Widgets.ActionPlan",
        "methodToExecute": "refresh"
    },
    {
        "typeName": "Sharedo.Core.Case.Widgets.KeyFacts",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Menus.Widgets.TabNav",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Widgets.KeyFacts",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.FormBuilder.Widgets.Standard",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Participants.ParticipantSummary",
        "methodToExecute": "loadAndBind"
    },
    // {
    //     "typeName": "Sharedo.Core.Case.Widgets.Comments",   //Comment has no methods and work on events we cannot tap into yet
    //     "methodToExecute": "loadAndBind"
    // },
    {
        "typeName": "Sharedo.Core.Case.Widgets.KeyDatesList_V2",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.ListViews.ListViewWidget",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Menus.Widgets.TopNav",
        "methodToExecute": "loadAndBind"
    },
];

export const otherWidgets=[
    {
        "typeName": "Sharedo.Core.Case.Menus.Widgets.LeftNavCaseProfile",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Menus.Widgets.WorkItemRibbon",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Menus.Widgets.TabNav",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Widgets.KeyFacts",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.FormBuilder.Widgets.Standard",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Participants.ParticipantSummary",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Participants.ParticipantSummary",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Sharedo.Widgets.InformationMessage",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Participants.ParticipantSummary",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Sharedo.CaseExplorer",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Widgets.Logo",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Sharedo.Widgets.RelatedDocuments",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Widgets.Comments",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Menus.Widgets.LeftNav",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Widgets.KeyDatesList_V2",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Visualisation.Widgets.ActionPlan",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "PortalWidgets.SharedoEventSync",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "PortalWidgets.SharedoEventSync",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Legal.Widgets.PhasePlan",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.ListViews.ListViewWidget",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.DataQuality.CaseWidget",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.FormBuilder.Widgets.Standard",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Widgets.UserProfile",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Widgets.NotificationsQuickView",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Menus.Widgets.TopNav",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Widgets.StopwatchQuickView",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.SearchScopes.QuickSearchNavBar",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.ListViews.FilterPanels.HierarchyFilter",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Participants.ParticipantFinderResultsList",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Participants.ParticipantFinderResultsList",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Participants.ParticipantFinderResultsList",
        "methodToExecute": "loadAndBind"
    },
    {
        "typeName": "Sharedo.Core.Case.Widgets.ActionPlan",
        "methodToExecute": "loadAndBind"
    }
]

export const REFRESH_WATCHER_FORMIO = {
    "_id": "650cc8d5e4f0d54921a6c8ec",
    "title": "Designer",
    "name": "designer",
    "path": "designer",
    "type": "form",
    "display": "form",
    "tags": [],
    "components": [
        {
            "label": "Configuration",
            "modalEdit": false,
            "key": "configuration",
            "type": "well",
            "input": false,
            "tableView": false,
            "components": [
                {
                    "label": "Disabled",
                    "tableView": false,
                    "key": "disabled",
                    "type": "checkbox",
                    "input": true,
                    "defaultValue": false,
                    "id": "epkmp88",
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "protected": false,
                    "unique": false,
                    "persistent": true,
                    "hidden": false,
                    "clearOnHide": true,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "dataGridLabel": true,
                    "labelPosition": "right",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "calculateServer": false,
                    "widget": null,
                    "attributes": {},
                    "validateOn": "change",
                    "validate": {
                        "required": false,
                        "custom": "",
                        "customPrivate": false,
                        "strictDateValidation": false,
                        "multiple": false,
                        "unique": false
                    },
                    "conditional": {
                        "show": null,
                        "when": null,
                        "eq": ""
                    },
                    "overlay": {
                        "style": "",
                        "left": "",
                        "top": "",
                        "width": "",
                        "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "addons": [],
                    "inputType": "checkbox",
                    "value": "",
                    "name": ""
                },
                {
                    "label": "Add Defaults",
                    "action": "event",
                    "showValidations": false,
                    "tableView": false,
                    "key": "addDefaults",
                    "type": "button",
                    "input": true,
                    "event": "AddDefaults",
                    "id": "e6uhdwc",
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "defaultValue": null,
                    "protected": false,
                    "unique": false,
                    "persistent": false,
                    "hidden": false,
                    "clearOnHide": true,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "dataGridLabel": true,
                    "labelPosition": "top",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "calculateServer": false,
                    "widget": {
                        "type": "input"
                    },
                    "attributes": {},
                    "validateOn": "change",
                    "validate": {
                        "required": false,
                        "custom": "",
                        "customPrivate": false,
                        "strictDateValidation": false,
                        "multiple": false,
                        "unique": false
                    },
                    "conditional": {
                        "show": null,
                        "when": null,
                        "eq": ""
                    },
                    "overlay": {
                        "style": "",
                        "left": "",
                        "top": "",
                        "width": "",
                        "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "addons": [],
                    "size": "md",
                    "leftIcon": "",
                    "rightIcon": "",
                    "block": false,
                    "theme": "primary"
                },
                {
                    "label": "Widgets To Refresh",
                    "reorder": false,
                    "addAnother": "Add",
                    "addAnotherPosition": "bottom",
                    "layoutFixed": false,
                    "enableRowGroups": false,
                    "initEmpty": false,
                    "tableView": false,
                    "defaultValue": [
                        {
                            "typeName": "",
                            "methodToExecute": ""
                        }
                    ],
                    "key": "widgets",
                    "type": "datagrid",
                    "input": true,
                    "components": [
                        {
                            "label": "Type Name",
                            "placeholder": "Sharedo.Core.Case.Menus.Widgets.WorkItemRibbon",
                            "applyMaskOn": "change",
                            "columnWeight": 0,
                            "hideColumnByDefault": false,
                            "disableSortingAndFiltering": false,
                            "tableView": true,
                            "key": "typeName",
                            "type": "textfield",
                            "input": true,
                            "id": "ec329ma",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "defaultValue": null,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "dataGridLabel": false,
                            "labelPosition": "top",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "widget": {
                                "type": "input"
                            },
                            "attributes": {},
                            "validateOn": "change",
                            "validate": {
                                "required": false,
                                "custom": "",
                                "customPrivate": false,
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false,
                                "minLength": "",
                                "maxLength": "",
                                "pattern": ""
                            },
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": ""
                            },
                            "overlay": {
                                "style": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "addons": [],
                            "mask": false,
                            "inputType": "text",
                            "inputFormat": "plain",
                            "inputMask": "",
                            "displayMask": "",
                            "spellcheck": true,
                            "truncateMultipleSpaces": false
                        },
                        {
                            "label": "Method to Execute",
                            "placeholder": "loadAndBind",
                            "applyMaskOn": "change",
                            "columnWeight": 0,
                            "hideColumnByDefault": false,
                            "disableSortingAndFiltering": false,
                            "tableView": true,
                            "key": "methodToExecute",
                            "type": "textfield",
                            "input": true,
                            "id": "eak5eu",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "defaultValue": null,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "dataGridLabel": false,
                            "labelPosition": "top",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "widget": {
                                "type": "input"
                            },
                            "attributes": {},
                            "validateOn": "change",
                            "validate": {
                                "required": false,
                                "custom": "",
                                "customPrivate": false,
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false,
                                "minLength": "",
                                "maxLength": "",
                                "pattern": ""
                            },
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": ""
                            },
                            "overlay": {
                                "style": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "addons": [],
                            "mask": false,
                            "inputType": "text",
                            "inputFormat": "plain",
                            "inputMask": "",
                            "displayMask": "",
                            "spellcheck": true,
                            "truncateMultipleSpaces": false
                        }
                    ],
                    "id": "euhfcwq",
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "protected": false,
                    "unique": false,
                    "persistent": true,
                    "hidden": false,
                    "clearOnHide": true,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "dataGridLabel": false,
                    "labelPosition": "top",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "calculateServer": false,
                    "widget": null,
                    "attributes": {},
                    "validateOn": "change",
                    "validate": {
                        "required": false,
                        "custom": "",
                        "customPrivate": false,
                        "strictDateValidation": false,
                        "multiple": false,
                        "unique": false
                    },
                    "conditional": {
                        "show": null,
                        "when": null,
                        "eq": ""
                    },
                    "overlay": {
                        "style": "",
                        "left": "",
                        "top": "",
                        "width": "",
                        "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "addons": [],
                    "tree": true,
                    "lazyLoad": false,
                    "disableAddingRemovingRows": false
                },
                {
                    "label": "Use Interval ( refresh every x seconds )",
                    "tableView": false,
                    "key": "useIntervalRefreshEveryXSeconds",
                    "type": "checkbox",
                    "input": true,
                    "defaultValue": false,
                    "id": "elxosc9",
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "protected": false,
                    "unique": false,
                    "persistent": true,
                    "hidden": false,
                    "clearOnHide": true,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "dataGridLabel": true,
                    "labelPosition": "right",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "calculateServer": false,
                    "widget": null,
                    "attributes": {},
                    "validateOn": "change",
                    "validate": {
                        "required": false,
                        "custom": "",
                        "customPrivate": false,
                        "strictDateValidation": false,
                        "multiple": false,
                        "unique": false
                    },
                    "conditional": {
                        "show": null,
                        "when": null,
                        "eq": ""
                    },
                    "overlay": {
                        "style": "",
                        "left": "",
                        "top": "",
                        "width": "",
                        "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "addons": [],
                    "inputType": "checkbox",
                    "value": "",
                    "name": ""
                },
                {
                    "label": "Interval (seconds)",
                    "applyMaskOn": "change",
                    "mask": false,
                    "tableView": false,
                    "delimiter": false,
                    "requireDecimal": false,
                    "inputFormat": "plain",
                    "truncateMultipleSpaces": false,
                    "key": "intervalSeconds",
                    "conditional": {
                        "show": true,
                        "conjunction": "all",
                        "conditions": [
                            {
                                "component": "useIntervalRefreshEveryXSeconds",
                                "operator": "isEqual",
                                "value": true
                            }
                        ],
                        "when": null,
                        "eq": ""
                    },
                    "type": "number",
                    "input": true,
                    "id": "evzsb3h",
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "defaultValue": null,
                    "protected": false,
                    "unique": false,
                    "persistent": true,
                    "hidden": false,
                    "clearOnHide": true,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "dataGridLabel": false,
                    "labelPosition": "top",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "calculateServer": false,
                    "widget": {
                        "type": "input"
                    },
                    "attributes": {},
                    "validateOn": "change",
                    "validate": {
                        "required": false,
                        "custom": "",
                        "customPrivate": false,
                        "strictDateValidation": false,
                        "multiple": false,
                        "unique": false,
                        "min": "",
                        "max": "",
                        "step": "any",
                        "integer": ""
                    },
                    "overlay": {
                        "style": "",
                        "left": "",
                        "top": "",
                        "width": "",
                        "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "addons": []
                },
                {
                    "label": "Optional Paths to Monitor ",
                    "labelPosition": "top",
                    "description": "",
                    "tooltip": "",
                    "disableAddingRemovingRows": false,
                    "conditionalAddButton": "",
                    "reorder": false,
                    "addAnother": "",
                    "addAnotherPosition": "bottom",
                    "layoutFixed": false,
                    "enableRowGroups": false,
                    "initEmpty": false,
                    "customClass": "",
                    "tabindex": "",
                    "hidden": false,
                    "hideLabel": false,
                    "autofocus": false,
                    "disabled": false,
                    "tableView": false,
                    "modalEdit": false,
                    "defaultValue": [
                        {}
                    ],
                    "persistent": true,
                    "protected": false,
                    "dbIndex": false,
                    "encrypted": false,
                    "redrawOn": "",
                    "clearOnHide": true,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "calculateServer": false,
                    "allowCalculateOverride": false,
                    "validateOn": "change",
                    "validate": {
                        "required": false,
                        "minLength": "",
                        "maxLength": "",
                        "customMessage": "",
                        "custom": "",
                        "customPrivate": false,
                        "json": "",
                        "strictDateValidation": false,
                        "multiple": false,
                        "unique": false
                    },
                    "validateWhenHidden": false,
                    "errorLabel": "",
                    "errors": "",
                    "key": "optionalPathsToMonitor",
                    "tags": [],
                    "properties": {},
                    "conditional": {
                        "show": null,
                        "conjunction": "",
                        "conditions": [],
                        "json": "",
                        "when": null,
                        "eq": ""
                    },
                    "customConditional": "",
                    "logic": [],
                    "attributes": {},
                    "overlay": {
                        "style": "",
                        "page": "",
                        "left": "",
                        "top": "",
                        "width": "",
                        "height": ""
                    },
                    "type": "datagrid",
                    "dataGridLabel": false,
                    "input": true,
                    "placeholder": "",
                    "prefix": "",
                    "suffix": "",
                    "multiple": false,
                    "unique": false,
                    "refreshOn": "",
                    "widget": null,
                    "showCharCount": false,
                    "showWordCount": false,
                    "allowMultipleMasks": false,
                    "addons": [],
                    "tree": true,
                    "lazyLoad": false,
                    "components": [
                        {
                            "label": "Path",
                            "labelPosition": "top",
                            "placeholder": "",
                            "description": "",
                            "tooltip": "",
                            "prefix": "",
                            "suffix": "",
                            "widget": {
                                "type": "input"
                            },
                            "inputMask": "",
                            "displayMask": "",
                            "applyMaskOn": "change",
                            "allowMultipleMasks": false,
                            "customClass": "",
                            "tabindex": "",
                            "autocomplete": "",
                            "hidden": false,
                            "hideLabel": false,
                            "showWordCount": false,
                            "showCharCount": false,
                            "mask": false,
                            "autofocus": false,
                            "spellcheck": true,
                            "dataGridLabel": false,
                            "disabled": false,
                            "tableView": true,
                            "modalEdit": false,
                            "multiple": false,
                            "persistent": true,
                            "inputFormat": "plain",
                            "protected": false,
                            "dbIndex": false,
                            "case": "",
                            "truncateMultipleSpaces": false,
                            "encrypted": false,
                            "redrawOn": "",
                            "clearOnHide": true,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "allowCalculateOverride": false,
                            "validateOn": "change",
                            "validate": {
                                "required": false,
                                "pattern": "",
                                "customMessage": "",
                                "custom": "",
                                "customPrivate": false,
                                "json": "",
                                "minLength": "",
                                "maxLength": "",
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false
                            },
                            "unique": false,
                            "validateWhenHidden": false,
                            "errorLabel": "",
                            "errors": "",
                            "key": "pathToMonitor",
                            "tags": [],
                            "properties": {},
                            "conditional": {
                                "show": null,
                                "conjunction": "",
                                "conditions": [],
                                "json": "",
                                "when": null,
                                "eq": ""
                            },
                            "customConditional": "",
                            "logic": [],
                            "attributes": {},
                            "overlay": {
                                "style": "",
                                "page": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                            },
                            "type": "textfield",
                            "input": true,
                            "refreshOn": "",
                            "addons": [],
                            "inputType": "text",
                            "id": "e9d97zr",
                            "defaultValue": ""
                        }
                    ],
                    "id": "esu5ptu"
                },
                {
                    "label": "Show Update Indicator",
                    "description": "",
                    "tooltip": "",
                    "shortcut": "",
                    "inputType": "checkbox",
                    "customClass": "",
                    "tabindex": "",
                    "hidden": false,
                    "hideLabel": false,
                    "autofocus": false,
                    "disabled": false,
                    "tableView": false,
                    "modalEdit": false,
                    "persistent": true,
                    "protected": false,
                    "dbIndex": false,
                    "encrypted": false,
                    "redrawOn": "",
                    "clearOnHide": true,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "calculateServer": false,
                    "allowCalculateOverride": false,
                    "validate": {
                        "required": false,
                        "customMessage": "",
                        "custom": "",
                        "customPrivate": false,
                        "json": "",
                        "strictDateValidation": false,
                        "multiple": false,
                        "unique": false
                    },
                    "validateWhenHidden": false,
                    "errorLabel": "",
                    "errors": "",
                    "key": "showUpdateIndicator",
                    "tags": [],
                    "properties": {},
                    "conditional": {
                        "show": true,
                        "conjunction": "all",
                        "conditions": [ ],
                        "json": "",
                        "when": null,
                        "eq": ""
                    },
                    "customConditional": "",
                    "logic": [],
                    "attributes": {},
                    "overlay": {
                        "style": "",
                        "page": "",
                        "left": "",
                        "top": "",
                        "width": "",
                        "height": ""
                    },
                    "type": "checkbox",
                    "name": "",
                    "value": "",
                    "dataGridLabel": true,
                    "input": true,
                    "placeholder": "",
                    "prefix": "",
                    "suffix": "",
                    "multiple": false,
                    "unique": false,
                    "refreshOn": "",
                    "labelPosition": "right",
                    "widget": null,
                    "validateOn": "change",
                    "showCharCount": false,
                    "showWordCount": false,
                    "allowMultipleMasks": false,
                    "addons": [],
                    "id": "ed5r28q",
                    "defaultValue": false
                },
                 {
                    "label": "Update Indicator Text",
                    "description": "",
                    "tooltip": "",
                    "shortcut": "",
                    "inputType": "text",
                    "customClass": "",
                    "tabindex": "",
                    "hidden": false,
                    "hideLabel": false,
                    "autofocus": false,
                    "disabled": false,
                    "tableView": false,
                    "modalEdit": false,
                    "persistent": true,
                    "protected": false,
                    "dbIndex": false,
                    "encrypted": false,
                    "redrawOn": "",
                    "clearOnHide": true,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "calculateServer": false,
                    "allowCalculateOverride": false,
                    "validate": {
                        "required": false,
                        "customMessage": "",
                        "custom": "",
                        "customPrivate": false,
                        "json": "",
                        "strictDateValidation": false,
                        "multiple": false,
                        "unique": false
                    },
                    "validateWhenHidden": false,
                    "errorLabel": "",
                    "errors": "",
                    "key": "indicatorText",
                    "tags": [],
                    "properties": {},
                    "conditional": {
                        "show": true,
                        "conjunction": "all",
                        "conditions": [ ],
                        "json": "",
                        "when": null,
                        "eq": ""
                    },
                    "customConditional": "",
                    "logic": [],
                    "attributes": {},
                    "overlay": {
                        "style": "",
                        "page": "",
                        "left": "",
                        "top": "",
                        "width": "",
                        "height": ""
                    },
                    "type": "textfield",
                    "name": "",
                    "value": "",
                    "dataGridLabel": true,
                    "input": true,
                    "placeholder": "",
                    "prefix": "",
                    "suffix": "",
                    "multiple": false,
                    "unique": false,
                    "refreshOn": "",
                    "labelPosition": "right",
                    "widget": null,
                    "validateOn": "change",
                    "showCharCount": false,
                    "showWordCount": false,
                    "allowMultipleMasks": false,
                    "addons": [],
                    "id": "ed5r28q",
                    "defaultValue": false
                },
                {
                    "label": "Refresh on events",
                    "tableView": false,
                    "key": "refreshOnEvents",
                    "type": "checkbox",
                    "input": true,
                    "defaultValue": false,
                    "id": "e4dfg6",
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "protected": false,
                    "unique": false,
                    "persistent": true,
                    "hidden": false,
                    "clearOnHide": true,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "dataGridLabel": true,
                    "labelPosition": "right",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "calculateServer": false,
                    "widget": null,
                    "attributes": {},
                    "validateOn": "change",
                    "validate": {
                        "required": false,
                        "custom": "",
                        "customPrivate": false,
                        "strictDateValidation": false,
                        "multiple": false,
                        "unique": false
                    },
                    "conditional": {
                        "show": null,
                        "when": null,
                        "eq": ""
                    },
                    "overlay": {
                        "style": "",
                        "left": "",
                        "top": "",
                        "width": "",
                        "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "addons": [],
                    "inputType": "checkbox",
                    "value": "",
                    "name": ""
                },
                {
                    "label": "Events To Listen To",
                    "reorder": false,
                    "addAnotherPosition": "bottom",
                    "layoutFixed": false,
                    "enableRowGroups": false,
                    "initEmpty": false,
                    "tableView": true,
                    "defaultValue": [
                        {
                            "eventName": ""
                        }
                    ],
                    "key": "eventsToListenTo",
                    "conditional": {
                        "show": true,
                        "conjunction": "all",
                        "conditions": [
                            {
                                "component": "refreshOnEvents",
                                "operator": "isEqual",
                                "value": true
                            }
                        ],
                        "when": null,
                        "eq": ""
                    },
                    "type": "datagrid",
                    "columnWeight": 0,
                    "hideColumnByDefault": false,
                    "disableSortingAndFiltering": false,
                    "input": true,
                    "components": [
                        {
                            "label": "Event Name",
                            "widget": "html5",
                            "tableView": false,
                            "dataSrc": "custom",
                            "data": {
                                "custom": "return dataContext.eventsOptions",
                                "values": [
                                    {
                                        "label": "",
                                        "value": ""
                                    }
                                ],
                                "json": "",
                                "url": "",
                                "resource": ""
                            },
                            "dataType": "auto",
                            "template": "<span>{{ item }}</span>",
                            "key": "eventName",
                            "type": "select",
                            "input": true,
                            "id": "en2bht",
                            "placeholder": "",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "defaultValue": null,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "dataGridLabel": false,
                            "labelPosition": "top",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "attributes": {},
                            "validateOn": "change",
                            "validate": {
                                "required": false,
                                "custom": "",
                                "customPrivate": false,
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false,
                                "onlyAvailableItems": false
                            },
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": ""
                            },
                            "overlay": {
                                "style": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "addons": [],
                            "authenticate": false,
                            "ignoreCache": false,
                            "idPath": "id",
                            "clearOnRefresh": false,
                            "limit": 100,
                            "valueProperty": "",
                            "lazyLoad": true,
                            "filter": "",
                            "searchEnabled": true,
                            "searchDebounce": 0.3,
                            "searchField": "",
                            "minSearch": 0,
                            "readOnlyValue": false,
                            "selectFields": "",
                            "selectThreshold": 0.3,
                            "uniqueOptions": false,
                            "fuseOptions": {
                                "include": "score",
                                "threshold": 0.3
                            },
                            "indexeddb": {
                                "filter": {}
                            },
                            "customOptions": {},
                            "useExactSearch": false
                        }
                    ],
                    "id": "edygu5n",
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "protected": false,
                    "unique": false,
                    "persistent": true,
                    "hidden": false,
                    "clearOnHide": true,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "dataGridLabel": false,
                    "labelPosition": "top",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "calculateServer": false,
                    "widget": null,
                    "attributes": {},
                    "validateOn": "change",
                    "validate": {
                        "required": false,
                        "custom": "",
                        "customPrivate": false,
                        "strictDateValidation": false,
                        "multiple": false,
                        "unique": false
                    },
                    "overlay": {
                        "style": "",
                        "left": "",
                        "top": "",
                        "width": "",
                        "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "addons": [],
                    "tree": true,
                    "lazyLoad": false,
                    "disableAddingRemovingRows": false
                }
            ],
            "id": "ehz1zb",
            "placeholder": "",
            "prefix": "",
            "customClass": "",
            "suffix": "",
            "multiple": false,
            "defaultValue": null,
            "protected": false,
            "unique": false,
            "persistent": false,
            "hidden": false,
            "clearOnHide": true,
            "refreshOn": "",
            "redrawOn": "",
            "dataGridLabel": false,
            "labelPosition": "top",
            "description": "",
            "errorLabel": "",
            "tooltip": "",
            "hideLabel": false,
            "tabindex": "",
            "disabled": false,
            "autofocus": false,
            "dbIndex": false,
            "customDefaultValue": "",
            "calculateValue": "",
            "calculateServer": false,
            "widget": null,
            "attributes": {},
            "validateOn": "change",
            "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
            },
            "conditional": {
                "show": null,
                "when": null,
                "eq": ""
            },
            "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
            },
            "allowCalculateOverride": false,
            "encrypted": false,
            "showCharCount": false,
            "showWordCount": false,
            "properties": {},
            "allowMultipleMasks": false,
            "addons": [],
            "tree": false,
            "lazyLoad": false
        },
        {
            "label": "Submit",
            "showValidations": false,
            "disableOnInvalid": true,
            "hidden": true,
            "tableView": false,
            "key": "submit",
            "type": "button",
            "input": true,
            "saveOnEnter": false,
            "id": "ewr7fsb",
            "placeholder": "",
            "prefix": "",
            "customClass": "",
            "suffix": "",
            "multiple": false,
            "defaultValue": null,
            "protected": false,
            "unique": false,
            "persistent": false,
            "clearOnHide": true,
            "refreshOn": "",
            "redrawOn": "",
            "modalEdit": false,
            "dataGridLabel": true,
            "labelPosition": "top",
            "description": "",
            "errorLabel": "",
            "tooltip": "",
            "hideLabel": false,
            "tabindex": "",
            "disabled": false,
            "autofocus": false,
            "dbIndex": false,
            "customDefaultValue": "",
            "calculateValue": "",
            "calculateServer": false,
            "widget": {
                "type": "input"
            },
            "attributes": {},
            "validateOn": "change",
            "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
            },
            "conditional": {
                "show": null,
                "when": null,
                "eq": ""
            },
            "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
            },
            "allowCalculateOverride": false,
            "encrypted": false,
            "showCharCount": false,
            "showWordCount": false,
            "properties": {},
            "allowMultipleMasks": false,
            "addons": [],
            "size": "md",
            "leftIcon": "",
            "rightIcon": "",
            "block": false,
            "action": "submit",
            "theme": "primary"
        }
    ],
    "settings": {}
}